# Generated by Django 3.0.3 on 2020-03-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_site',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
